### ISSUE TITLE
License unclear

### ISSUE THREAD

**Issue by rbarbey** [scottymarshall/pingfederate#3]
Hey @scottymarshall,

could you please clarify the license of this cookbook? In the `metadata.rb` file, the license is set to `all_rights` which according to other Ruby resources means "All rights reserved. Do not redistribute". On the other hand, the `metadata.rb` file looks a bit auto-generated so it would be great if you could clarify the license for this cookbook.

Thanks and best,
Robert

**Comment by scottymarshall** [comment]
Hi @rbarbey,
I just removed the license line for now.  Feel free to distribute.  If I do get a license, it will be an Apache license.
